device-editor-octoblu:
  container_name: device-editor-octoblu
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./device-editor-octoblu-local.env
