cwc-auth-staging:
  container_name: cwc-auth-staging
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-authenticator-cwc-staging-local.env
