data-forwarders:
  container_name: data-forwarders
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./data-forwarders-local.env
