{{{containerName}}}:
  container_name: {{{containerName}}}
  build: ${HOME}/Projects/Octoblu/{{{projectName}}}
  dockerfile: .{{{projectName}}}.dockerfile-dev
{{#each compose}}
  {{{this}}}
{{/each}}
  ports:
   - "$SERVICE_PORT"

  labels:
    traefik.port: "80"

  dns: "$DNS"

{{#if links}}
  external_links:
{{#each links}}
    - {{{this}}}
{{/each}}

{{/if}}
  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/{{{projectName}}}:/usr/src/app

  env_file:
    - ./{{{projectName}}}-public.env
    - ./{{{projectName}}}-private.env
    - ./{{{projectName}}}-local.env
