{{{containerName}}}:
  container_name: {{{containerName}}}
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./{{{projectName}}}-local.env
