nanocyte-flow-deploy:
  container_name: nanocyte-flow-deploy
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./nanocyte-flow-deploy-service-local.env
