meshblu-authenticator-email-password:
  container_name: meshblu-authenticator-email-password
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-authenticator-email-password-local.env
