meshblu-socket-io:
  container_name: meshblu-socket-io
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-server-socket.io-v1-local.env
