app:
  container_name: app
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./app-octoblu-local.env
