meshblu-xmpp:
  container_name: meshblu-xmpp
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-core-protocol-adapter-xmpp-local.env
