oauth:
  container_name: oauth
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./oauth-provider-local.env
