nanocyte-interval-redis:
  container_name: nanocyte-interval-redis
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./nanocyte-interval-redis-local.env
