nanocyte-interval:
  container_name: nanocyte-interval
  build: ${HOME}/Projects/Octoblu/nanocyte-interval-service
  dockerfile: .nanocyte-interval-service.dockerfile-dev
  ports:
   - "80"

  labels:
    traefik.port: "80"

  dns: "$DNS"

  external_links:
    - redis-tmp:redis

  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/nanocyte-interval-service:/usr/src/app

  env_file:
    - ./nanocyte-interval-service-public.env
    - ./nanocyte-interval-service-private.env
