meshblu-firehose-socket-io:
  container_name: meshblu-firehose-socket-io
  build: ${HOME}/Projects/Octoblu/meshblu-core-firehose-socket.io
  dockerfile: .meshblu-core-firehose-socket.io.dockerfile-dev
  ports:
   - "80"

  labels:
    traefik.port: "80"

  dns: "$DNS"

  external_links:
    - redis-tmp:redis.dev

  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/meshblu-core-firehose-socket.io:/usr/src/app

  env_file:
    - ./meshblu-core-firehose-socket.io-public.env
    - ./meshblu-core-firehose-socket.io-private.env
    - ./meshblu-core-firehose-socket.io-local.env
