meshblu:
  container_name: meshblu
  build: ${HOME}/Projects/Octoblu/meshblu-haproxy
  dockerfile: .meshblu-haproxy.dockerfile-dev
  ports:
   - "$SERVICE_PORT"

  labels:
    traefik.port: "80"

  dns: "$DNS"

  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/meshblu-haproxy:/usr/src/app

  env_file:
    - ./meshblu-haproxy-public.env
    - ./meshblu-haproxy-private.env
    - ./meshblu-haproxy-local.env
