mongodb-forwarder:
  container_name: mongodb-forwarder
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-mongodb-forwarder-local.env
