meshblu:
  container_name: meshblu
  build: ${HOME}/Projects/Octoblu/meshblu-haproxy
  dockerfile: Dockerfile-dev
  ports:
   - "80"

  labels:
    traefik.port: "80"

  dns: "192.168.99.1"

  volumes:
    - /usr/src/app/node_modules
    # - ${HOME}/Projects/Octoblu/meshblu-haproxy:/usr/src/app

  env_file:
    - ./meshblu-haproxy-public.env
    - ./meshblu-haproxy-private.env
