nanocyte-flow-deploy:
  container_name: "nanocyte-flow-deploy"
  build: ${HOME}/Projects/Octoblu/nanocyte-flow-deploy-service
  ports:
   - "80"

  labels:
    traefik.port: "80"

  dns: "192.168.99.1"

  external_links:
    - redis-tmp:redis

  volumes:
    - /usr/src/app/node_modules
    - ${HOME}/Projects/Octoblu/nanocyte-flow-deploy-service:/usr/src/app

  env_file:
    - ./nanocyte-flow-deploy-service.env
