nanocyte-node-registry:
  container_name: "nanocyte-node-registry"
  build: ${HOME}/Projects/Octoblu/nanocyte-node-registry
  ports:
   - "80"

  labels:
    traefik.port: "80"

  # dns: "192.168.99.1"

  external_links:
    - redis-tmp:redis

  volumes:
    - /usr/src/app/node_modules
    - ${HOME}/Projects/Octoblu/nanocyte-node-registry:/usr/src/app

  env_file:
    - ./nanocyte-node-registry.env
