nanocyte-engine-http:
  container_name: nanocyte-engine-http
  build: ${HOME}/Projects/Octoblu/nanocyte-engine-http
  dockerfile: .nanocyte-engine-http.dockerfile-dev
  ports:
   - "$SERVICE_PORT"

  labels:
    traefik.port: "80"

  dns: "$DNS"

  external_links:
    - redis-tmp:redis.dev

  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/nanocyte-engine-http:/usr/src/app

  env_file:
    - ./nanocyte-engine-http-public.env
    - ./nanocyte-engine-http-private.env
    - ./nanocyte-engine-http-local.env
