nanocyte-engine-worker:
  container_name: nanocyte-engine-worker
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./nanocyte-engine-worker-local.env
