meshblu-core-dispatcher:
  container_name: meshblu-core-dispatcher
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-core-dispatcher-local.env
