meshblu-core-dispatcher-whisreset:
  container_name: meshblu-core-dispatcher-whisreset
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-core-dispatcher-whisreset-local.env
