meshblu-core-dispatcher-tango:
  container_name: meshblu-core-dispatcher-tango
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-core-dispatcher-tango-local.env
