{{{domainName}}}:
  container_name: {{{domainName}}}
  build: ${HOME}/Projects/Octoblu/{{{projectName}}}
{{#each compose}}
  {{{this}}}
{{/each}}
  ports:
   - "80"

  labels:
    traefik.port: "80"

  dns: "192.168.99.1"

{{#if links}}
  external_links:
{{#each links}}
    - {{{this}}}
{{/each}}

{{/if}}
  volumes:
    - /usr/src/app/node_modules
    # - ${HOME}/Projects/Octoblu/{{{projectName}}}:/usr/src/app

  env_file:
    - ./{{{projectName}}}-public.env
    - ./{{{projectName}}}-private.env
