cwc-authenticator-proxy:
  container_name: cwc-authenticator-proxy
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./cwc-authenticator-proxy-service-local.env
