email-password-site:
  container_name: email-password-site
  build: ${HOME}/Projects/Octoblu/email-password-site
  dockerfile: .email-password-site.dockerfile-dev
  ports:
   - "80"

  labels:
    traefik.port: "80"

  dns: "$DNS"

  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/email-password-site:/usr/src/app

  env_file:
    - ./email-password-site-public.env
    - ./email-password-site-private.env
    - ./email-password-site-local.env
