meshblu-core-worker-amqp:
  container_name: meshblu-core-worker-amqp
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "$LOCAL_PORT:$SERVICE_PORT"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-core-worker-amqp-local.env
