splunk-collector:
  container_name: splunk-collector
  build: ${HOME}/Projects/Octoblu/octoblu-dev/services/_local
  privileged: true

  ports:
   - "80"

  labels:
    traefik.port: "80"

  env_file:
    - ./meshblu-splunk-event-collector-local.env
