splunk-collector:
  container_name: splunk-collector
  build: ${HOME}/Projects/Octoblu/meshblu-splunk-event-collector
  dockerfile: .meshblu-splunk-event-collector.dockerfile-dev
  ports:
   - "$SERVICE_PORT"

  labels:
    traefik.port: "80"

  dns: "$DNS"

  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/meshblu-splunk-event-collector:/usr/src/app

  env_file:
    - ./meshblu-splunk-event-collector-public.env
    - ./meshblu-splunk-event-collector-private.env
    - ./meshblu-splunk-event-collector-local.env
