meshblu-amqp-auth:
  container_name: meshblu-amqp-auth
  build: ${HOME}/Projects/Octoblu/meshblu-amqp-auth-service
  dockerfile: .meshblu-amqp-auth-service.dockerfile-dev
  ports:
   - "$SERVICE_PORT"

  labels:
    traefik.port: "80"

  dns: "$DNS"

  volumes:
    - /usr/src/app/node_modules
    #- ${HOME}/Projects/Octoblu/meshblu-amqp-auth-service:/usr/src/app

  env_file:
    - ./meshblu-amqp-auth-service-public.env
    - ./meshblu-amqp-auth-service-private.env
    - ./meshblu-amqp-auth-service-local.env
